version: '3.1'

services:
  kalkun:
    image: devyag/kalkun-gammu:0.8d
    restart: always
    ports:
      - 8000:80
    devices:
      - /dev/ttyUSB0:/dev/gsm-modem
    depends_on:
      - "kalkun-db"

  kalkun-db:
    image: realjoshbyrnes/mariadb-kalkun:0.8d
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: RANDOM
      MYSQL_DATABASE: kalkun
      MYSQL_USER: kalkun
      MYSQL_PASSWORD: kalkun
    volumes:
      - kalkun_db:/var/lib/mysql

volumes:
  kalkun_db:
